models/Actor.php
<?php
namespace app\models;

class Actor extends \yii\db\ActiveRecord {
    // untuk validation
    public function rules() {
        return [
            [['first_name', 'last_name'], 'required'],
            ['first_name', 'string', 'min' => 3]
        ];
        // required = x boleh empty
    }
}

controllers/ActorController.php
<?php
namespace app\controllers;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
class ActorController extends \yii\web\Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    public function actionTestUtil() {
        echo unique_id();
        $ymd = \app\utility\Utility::dmy2ymd('28/09/2021');
        echo $ymd;
    }

    // list all actors. index.php?r=actor/list
    public function actionList() {
        $req = \Yii::$app->request;

        if ($req->isPost) {
            // search
            $name = $req->post('name');
            $query = \app\models\Actor::find()->where(['like', 'first_name', "%$name%", false]);
        } else {
            // click dari link / all
            $query = \app\models\Actor::find();
        }
        
        $recordCount = $query->count();
        $pagination = new Pagination(['totalCount' => $recordCount, 'defaultPageSize' => 10]);
        $actors = $query->offset($pagination->offset)->limit($pagination->limit)->all();
        return $this->render('list', ['actors' => $actors, 'pagination' => $pagination]);
    }

    // show form
    public function actionCreate() {
        $actor = new \app\models\Actor();
        return $this->render('form', ['actor' => $actor]);
    }

    public function actionSave() {
        $req = Yii::$app->request;
        $id = $req->post('actor_id');

        if (empty($id)) {
            // insert
            $actor = new \app\models\Actor(); // create a new actor
        } else {
            // update
            $actor = \app\models\Actor::findOne($id);
        }
        
        $actor->first_name = $req->post('first_name');
        $actor->last_name = $req->post('last_name');

        if ($actor->validate()) {
            // validation ok
            $actor->save(); // insert / update into actor
            return $this->redirect('index.php?r=actor/list');
        } else {
            // validation tak ok
            return $this->render('form', ['actor' => $actor]);
        }        
    }

    // index.php?r=actor/delete&actor_id=5
    public function actionDelete($actor_id) {
        echo $actor_id;
        \app\models\Actor::findOne($actor_id)->delete(); // findOne($id) = cari by primary key, return an obj
        return $this->redirect(['actor/list']);
    }

    public function actionEdit($actor_id) {
        $actor = \app\models\Actor::findOne($actor_id);
        return $this->render('form', ['actor' => $actor]);
    }
}

views/actor/form.php
<?php 
use yii\helpers\Url;
?>

<h1>Actor Form</h1>

<?php if ($actor->hasErrors()): ?>
    <div class="alert alert-danger">
        <?= \yii\helpers\Html::errorSummary($actor) ?>
    </div>
<?php endif; ?>

<form action="<?= Url::to(['actor/save']) ?>" method="post">
    <input type="hidden" name="_csrf" value="<?= \Yii::$app->request->csrfToken ?>">
    <input type="hidden" name="actor_id" value="<?= $actor->actor_id ?>">

    First Name : <input type="text" name="first_name" value="<?= $actor->first_name ?>">
    <br>
    Last Name : <input type="text" name="last_name" value="<?= $actor->last_name ?>">
    <br>
    <input type="submit" value="Save" >
</form>

views/actor/list.php
<?php
use yii\helpers\Url;
?>

<h1>Actor List</h1>

<form action="index.php?r=actor/list" method='post'>
    <input type="hidden" name="_csrf" value="<?= \Yii::$app->request->csrfToken ?>">
    Searh by Name : <input type="text" name="name">
    <input type='submit'>
</form>

<table class="table table-striped">
    <tr>
        <td>#</td>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Action</td>
    </tr>
    <?php
    $no = $pagination->getPage() * $pagination->getPageSize() + 1; 
    foreach($actors as $actor) : ?>
    <tr>
        <td><?= $no++ ?></td>
        <td><?= $actor->first_name ?></td>
        <td><?= $actor->last_name ?></td>
        <td>
            <a href="<?= Url::to(['actor/edit', 'actor_id' => $actor->actor_id]) ?>" class="btn btn-primary">Edit</a>
            <a href="<?= Url::to(['actor/delete', 'actor_id' => $actor->actor_id]) ?>" onclick="return confirm('Are you sure you want to delete')"class="btn btn-danger">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<?= \yii\widgets\LinkPager::widget([
    'pagination'   => $pagination,
    'pageCssClass' => 'page-item',
    'linkOptions'  => ['class' => 'page-link']
    ]) ?>